# Generated by Django 3.2.6 on 2021-09-19 02:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('cur_val', models.DecimalField(decimal_places=2, default=100000.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('portfolio_name', models.CharField(max_length=200)),
                ('balance', models.IntegerField(default=0)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Low medium', 'Low medium'), ('Medium', 'Medium'), ('Medium high', 'Medium high'), ('High', 'High')], max_length=200, null=True)),
                ('expected_return', models.FloatField(null=True)),
                ('investment_horizion', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Hold', 'Hold')], max_length=200, null=True)),
                ('ticker', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=10, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('price', models.CharField(default=3418.07, max_length=30)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='BT_RSI_Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 12, 31, 18, 0))),
                ('end', models.DateTimeField(default=datetime.datetime(2021, 5, 30, 19, 0))),
                ('strategy_name', models.CharField(default='Backtest RSI Strategy', max_length=200)),
                ('interval', models.CharField(choices=[('One Minute', 'One Minute'), ('Five Minute', 'Five Minute'), ('Fifteen Minute', 'Fifteen Minute'), ('One Hour', 'One Hour'), ('Half Day', 'Half Day'), ('One Day', 'One Day')], default='One Day', max_length=20)),
                ('timeframe', models.IntegerField(default=14)),
                ('frequency', models.IntegerField(default=86400)),
                ('begin_balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=20)),
                ('end_balance', models.DecimalField(blank=True, decimal_places=2, default=1250.0, max_digits=20)),
                ('overbought_threshold', models.DecimalField(decimal_places=2, default=70.0, max_digits=20)),
                ('oversold_threshold', models.DecimalField(decimal_places=2, default=30.0, max_digits=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
