# Generated by Django 3.2.6 on 2021-09-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.CharField(default=3431.23, max_length=30),
        ),
    ]
